# Generated by Django 5.2.6 on 2025-09-14 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ping', 'Lightweight (HEAD/GET ping)'), ('labs', 'Full (authenticate + list labs)')], default='ping', max_length=10)),
                ('check_interval_sec', models.PositiveIntegerField(default=30)),
                ('scheduler_tick_sec', models.PositiveIntegerField(default=1)),
                ('http_timeout_sec', models.PositiveIntegerField(default=12)),
                ('quick_retries', models.PositiveIntegerField(default=3)),
                ('quick_retry_delay_sec', models.PositiveIntegerField(default=5)),
                ('backoff_base_sec', models.PositiveIntegerField(default=15)),
                ('backoff_max_sec', models.PositiveIntegerField(default=300)),
                ('stats_interval_sec', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='PoolStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total', models.PositiveIntegerField()),
                ('available', models.PositiveIntegerField()),
                ('in_use', models.PositiveIntegerField()),
                ('unavailable', models.PositiveIntegerField()),
                ('initializing', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMLServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='Base API URL, e.g. https://host/api/v0')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('verify_tls', models.BooleanField(default=False, help_text='Verify TLS certificates (False for self-signed in dev)')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('unavailable', 'Unavailable'), ('initializing', 'Initializing')], default='initializing', max_length=20)),
                ('last_health_ok', models.BooleanField(default=False)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_lab_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('assigned_lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_until', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cml_servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
