# Generated by Django 5.2.6 on 2025-09-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0006_leaselog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaselog',
            new_name='orchestrato_created_8fbee9_idx',
            old_name='orchestrat_created_0f3331_idx',
        ),
        migrations.RenameIndex(
            model_name='leaselog',
            new_name='orchestrato_event_cbad41_idx',
            old_name='orchestrat_event_6ea86c_idx',
        ),
        migrations.RenameIndex(
            model_name='leaselog',
            new_name='orchestrato_usernam_58336d_idx',
            old_name='orchestrat_usernam_f2f9d9_idx',
        ),
        migrations.RenameIndex(
            model_name='leaselog',
            new_name='orchestrato_server__6a4475_idx',
            old_name='orchestrat_server__a6aa1f_idx',
        ),
    ]
