# Generated by Django 5.2.6 on 2025-09-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0007_rename_orchestrat_created_0f3331_idx_orchestrato_created_8fbee9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmlserver',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('unavailable', 'Unavailable'), ('initializing', 'Initializing'), ('maintenance', 'Maintenance')], default='initializing', max_length=20),
        ),
    ]
